import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Spec 028 FR-018/FR-019 (contracts/formatting-surface.md "The guard"):
/// no file outside the allowlist below may reach for date/number formatting
/// directly — every display path goes through `formattersProvider`
/// (`lib/core/formatting/`). Modeled on `test/unit/core/layering_test.dart`'s
/// scan pattern: a plain `dart:io` source scan, no new tooling.
///
/// Bans two signals, each sufficient on its own to reach `DateFormat`/
/// `NumberFormat` or hand-roll a decimal rendering:
///   1. `import 'package:intl/...'` anywhere in `lib/`.
///   2. `toStringAsFixed(` anywhere under a `presentation/` directory.
///
/// **Allowlist** (data-model.md §3) — each entry justified in-line:
/// - `lib/core/formatting/` — the surface itself.
/// - `lib/generated/` — generated OpenAPI client (constitution §III: never
///   hand-edited).
/// - `lib/l10n/app_localizations*.dart` — generated by `flutter gen-l10n`;
///   the output path comes from `l10n.yaml`, so a change there updates this
///   list (research.md R2 — this is *not* `lib/generated/`, a correction
///   from the carried-forward 027 design, which would have missed these).
/// - `lib/main.dart` — `initializeDateFormatting()`, the one-time app-startup
///   call `intl`'s `DateFormat` requires before any locale can be used.
/// - `lib/features/sales/presentation/pos_sales_list_controller.dart` —
///   `_dateFacetFormat` encodes a `yyyy-MM-dd` **URL query facet**, not a
///   display path, and must stay locale-independent.
///
/// If you are adding a new exemption, you are almost certainly adding a
/// display path that belongs in the surface instead.
void main() {
  const allowedIntlImporters = {
    'lib/main.dart',
    'lib/features/sales/presentation/pos_sales_list_controller.dart',
  };

  bool isAllowed(String path) {
    if (path.startsWith('lib/core/formatting/')) return true;
    if (path.startsWith('lib/generated/')) return true;
    if (path.startsWith('lib/l10n/app_localizations') && path.endsWith('.dart')) {
      return true;
    }
    return allowedIntlImporters.contains(path);
  }

  Iterable<File> dartFilesUnder(String dir) sync* {
    final root = Directory(dir);
    if (!root.existsSync()) return;
    for (final entity in root.listSync(recursive: true)) {
      if (entity is File && entity.path.endsWith('.dart')) yield entity;
    }
  }

  test('no file outside the allowlist imports package:intl', () {
    final offenders = <String>[];
    for (final file in dartFilesUnder('lib')) {
      // Normalize to forward-slash, repo-relative — matches the allowlist
      // entries above regardless of platform path separators.
      final path = file.path.replaceAll(r'\', '/');
      if (isAllowed(path)) continue;
      final contents = file.readAsStringSync();
      if (contents.contains("import 'package:intl/")) {
        offenders.add(path);
      }
    }
    expect(
      offenders,
      isEmpty,
      reason:
          'Every date/number formatting path must go through '
          'formattersProvider (lib/core/formatting/), not package:intl '
          'directly (spec 028 FR-018): ${offenders.join(', ')}',
    );
  });

  test('no presentation/ file calls toStringAsFixed( directly', () {
    final offenders = <String>[];
    for (final file in dartFilesUnder('lib')) {
      final path = file.path.replaceAll(r'\', '/');
      if (!path.contains('/presentation/')) continue;
      if (isAllowed(path)) continue;
      final contents = file.readAsStringSync();
      if (contents.contains('toStringAsFixed(')) {
        offenders.add(path);
      }
    }
    expect(
      offenders,
      isEmpty,
      reason:
          'A presentation/ file must format decimals through '
          'formattersProvider (lib/core/formatting/), not '
          'toStringAsFixed() directly (spec 028 FR-018): '
          '${offenders.join(', ')}',
    );
  });
}
