/// Permission-gate catalog mirroring mbe-api/legacy `SystemObjects`
/// (`mbe/docs/constants.md` §SystemObjects, DESIGN.md §3.7).
///
/// Each user has zero or one [Privilege] per [SystemObject]. Values `31`,
/// `70`, `76`-`78`, and `104`-`105` are intentionally absent — they are
/// disabled/unused in the legacy codebase and were never assigned a name.
/// Value `107` (`productionSites`) is also intentionally absent as of
/// spec 014: mbe-api merged the legacy Store and Production Site concepts
/// into `Facility`, reusing slot `29` (previously `stores`) as `FACILITIES`
/// and removing `PRODUCTION_SITES` entirely (mictlanix/mbe-api#93).
enum SystemObject {
  products(0),
  labels(1),
  customers(2),
  suppliers(3),
  warehouses(4),
  priceLists(5),
  employees(6),
  salesOrders(7),
  customerPayments(8),
  pointsOfSale(9),
  cashDrawers(10),
  addresses(11),
  contacts(12),
  bankAccounts(13),
  supplierAgreements(14),
  inventoryReceipts(15),
  inventoryIssues(16),
  inventoryTransfers(17),
  accountsReceivable(18),
  accountsPayable(19),
  purchasesOrders(20),
  supplierPayment(21),
  customerRefunds(22),
  fiscalDocuments(23),
  taxpayers(24),
  supplierReturns(25),
  salesOrdersHistoric(26),
  customerRefundsHistoric(27),
  supplierReturnHistoric(28),
  facilities(29),
  salesQuotes(30),
  kardex(32),
  receivedPayments(33),
  salesByCustomer(34),
  salesBySalesPerson(35),
  salesByProduct(36),
  grossProfitsByCustomer(37),
  grossProfitsBySalesPerson(38),
  grossProfitsByProduct(39),
  bestSellingProductsByCustomer(40),
  bestSellingProductsBySalesPerson(41),
  lotSerialNumbers(42),
  exchangeRates(43),
  pos(44),
  serialNumberKardex(45),
  customerDebtReport(46),
  salesOrderSummaryReport(47),
  fiscalDocumentsReport(48),
  salesPersonOrdersReport(49),
  customerSalesOrdersReport(50),
  productSalesByCustomerReport(51),
  productSalesByModelReport(52),
  productSalesByBrandReport(53),
  taxpayerRecipients(54),
  productSalesBySalesPerson(55),
  standaloneFiscalDocuments(56),
  productionOrders(57),
  technicalServiceReports(58),
  translationRequests(59),
  notarizations(60),
  productSalesBySalesPersonAndLabel(61),
  productSalesBySalesPersonAndBrand(62),
  productSalesBySalesPersonAndModel(63),
  technicalServiceRequests(64),
  technicalServiceReceipts(65),
  customersReport(66),
  warehouseStockReport(67),
  warehouseStockByLotReport(68),
  warehouseStockBySerialNumberReport(69),
  deliveryOrders(71),
  salesPersonOrdersAndRefundsReport(72),
  productsMerge(73),
  physicalCountAdjustment(74),
  productsBySupplierReport(75),
  productsOrdersAndRefundsBySalesPerson(79),
  pendantDeliveries(80),
  expenses(81),
  expenseTicket(82),
  creditPayments(83),
  paymentMethodOptions(84),
  paymentReceipt(85),
  purchaseRequest(86),
  deliveryItineraries(87),
  vehicle(88),
  vehicleOperators(89),
  vehicleServiceOrders(90),
  forDeliver(91),
  users(92),
  inventoryAdjustments(93),
  deliveryOrderApproval(94),
  purchaseOrderApproval(95),
  purchaseRequestApproval(96),
  receivedPaymentsAdvancedSearchFilter(97),
  creditCustomerConfiguration(98),
  storeMovementsSummary(99),
  paymentsEditor(100),
  searchCreditsFromAllStores(101),
  excludePriceRangeValidation(102),
  issuedLocationId(103),
  pricing(106),
  paymentsVerification(108),
  receivedPaymentsSummary(109),
  customerRefundConfirm(110),
  cashSessionClose(111),
  commissionsBySalesPerson(112),
  downloadCSVFiles(113);

  const SystemObject(this.value);

  final int value;

  /// Looks up the [SystemObject] whose [value] matches mbe-api's
  /// `system_object` integer (`PrivilegeResponse`/`PrivilegeUpdate`).
  static SystemObject? fromValue(int value) {
    for (final object in SystemObject.values) {
      if (object.value == value) return object;
    }
    return null;
  }
}
